//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfig
    {
        public int Id { get; set; }
        public string AppKey { get; set; }
        public string AppVaue { get; set; }
        public string Section { get; set; }
        public int SortOrder { get; set; }
        public string Caption { get; set; }
        public string HelpText { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
